AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >

Globals:
  Function:
    Timeout: 3

Resources:
  DBTABLE:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - 
          AttributeName: "FoodID"
          AttributeType: "S"
      KeySchema:
        - 
          AttributeName: "FoodID"
          KeyType: "HASH"
      ProvisionedThroughput: 
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TableName: "myFoodTable"

  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Role: !GetAtt LambdaRole.Arn
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /foods
            Method: get

        HelloWorldFood:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /food
            Method: post

  SignUpFunction:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          USER_POOL_CLIENT_ID:
            Ref: CognitoUserPoolClient
      CodeUri: signup/
      Handler: signup.lambda_handler
      Role: !GetAtt LambdaRole.Arn
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        SingingUp:
          Type: Api
          Properties:
            RestApiId: !Ref SignUpApi
            Path: /user
            Method: post

  LoginUpFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: signup/
      Handler: login.lambda_handler
      Environment:
        Variables:
          USER_POOL_ID:
            Ref: CognitoUserPool
          USER_POOL_CLIENT_ID:
            Ref: CognitoUserPoolClient
      Role: !GetAtt LambdaRole.Arn
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        LoggingIn:
          Type: Api
          Properties:
            RestApiId: !Ref SignUpApi
            Path: /user-info
            Method: post
  
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: sam-user-pool
      Policies:
        PasswordPolicy:
          MinimumLength: 8
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      Schema:
        - AttributeDataType: String
          Name: email
          Required: false

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: sam-user-pool-client
      UserPoolId: !Ref CognitoUserPool
      ExplicitAuthFlows:
        - ADMIN_NO_SRP_AUTH
      GenerateSecret: false

  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors: "'*'"
      Auth:
        DefaultAuthorizer: MyCognitoAuthorizer
        
        Authorizers:
          MyCognitoAuthorizer:
            UserPoolArn: !GetAtt CognitoUserPool.Arn

  SignUpApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors: "'*'"
      Auth:
        DefaultAuthorizer: MyCognitoAuthorizer
        
        Authorizers:
          MyCognitoAuthorizer:
            UserPoolArn: !GetAtt CognitoUserPool.Arn

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
          -
            PolicyName: LambdaRolePolicy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                -
                  Effect: Allow
                  Action:
                    - cognito-idp:AdminInitiateAuth
                    - dynamodb:CreateTable
                    - dynamodb:GetItem
                    - dynamodb:PutItem
                    - dynamodb:Scan
                    - lambda:InvokeFunction
                  Resource:
                    - !GetAtt DBTABLE.Arn
                    - !GetAtt CognitoUserPool.Arn
